class SummarizerAgent:
    """
    Agent responsible for processing HackerNews posts and generating summaries.
    
    This is a basic agent-based architecture:
    - Accepts clean post text
    - Processes it (currently returns dummy summary)
    - Returns summary string
    
    Later, this will be enhanced with AI capabilities.
    """
    
    def __init__(self):
        self.name = "HackerNews Summarizer Agent"
    
    def process(self, post_text: str) -> str:
        """
        Accept clean post text and return a summary.
        
        Currently returns a dummy summary for architecture testing just like " Agent Summary: This is a placeholder summary generated by the agent ".
        Later, this will call AI models (Gemini, OpenAI, Anthropic.)
        
        Args:
            post_text: Clean formatted text about a HackerNews post
            
        Returns:
            Summary string (dummy for now)
        """
        # Dummy processing - this proves the agent architecture works
        # Later, this will call AI models
        return "This is a placeholder summary generated by the agent."


def prepare_text_for_agent(story) -> str:
    """
    Convert a Story object into clean text format for the agent.
    This prepares input that will later be sent to AI models.
    The agent should NOT receive raw JSON - only clean, readable text.
    
    Args:
        story: Story object with post data
        
    Returns:
        Clean formatted text string
    """
    text = f"""Title: {story.title}
Author: {story.by}
Score: {story.score}
Comments: {story.descendants}
URL: {story.url or f"https://news.ycombinator.com/item?id={story.id}"}"""
    
    return text
