from praval import agent

@agent("hn_summarizer", responds_to=["summary_request"])
def hn_summary_agent(spore):
    """
    A simple Praval agent that receives text via spore
    and returns a placeholder summary.
    """
    # Extract text from spore knowledge
    text = spore.knowledge.get("text", "")
    
    print(f"Processing text: {text[:50]}...")
    
    # Return placeholder summary
    return {"summary": "This summary is generated by a Praval agent."}

